---
title: "DQDB Graph Pop-out Reporting"
output:
  html_document: default
  pdf_document: default
params:
  mindate: '2022-05-01'
  maxdate: '2022-05-01'
---

```{r setup, include=FALSE}
source("global.R")

library(janitor)

```


```{r summary, echo = FALSE, message = FALSE,  warning = FALSE, include = FALSE}

summary <- summary_tab_pulldown(params$mindate, params$maxdate)

```

```{r exceptions, echo = FALSE, message = FALSE,  warning = FALSE, include = FALSE}
exceptions <- exceptions_tab_pulldown(params$mindate, params$maxdate)


```

```{r cells, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
#Making a priority level vector just for example
pri_lvl <- c("1", "2")

cells <- cells_tab_pulldown(params$mindate, params$maxdate, pri_lvl)



```
```{r tables, echo = FALSE, message = FALSE}
flextable::flextable(summary) %>%    # convert to pretty image
   flextable::autofit() 

flextable::flextable(exceptions) %>%    # convert to pretty image
   flextable::autofit() 

flextable::flextable(cells) %>%    # convert to pretty image
   flextable::autofit() 
```


